name: demo-inputs
on:
  workflow_dispatch:
    inputs:
      print_modules:
        description: 'True to print modules to STDOUT'
        required: true 
        type: boolean 
      modules:
        description: 'python packages for pip'
        required: true 
        type: string

jobs:
  custom-pip:
    runs-on: macos-10.15
    steps:
      - name: install a package
        run: pip3 install ${{ github.event.inputs.modules }}

      - name: Display the path and version
        run: python3 --version

      - name: display pip packages
        if:  ${{ github.event.inputs.print_modules == 'true' }} 
        run: pip3 list



