name: demo-inputs
on:
  workflow_dispatch:
    inputs:
      print_modules:
        description: 'True to print to STDOUT'
        required: true 
        type: boolean 
      modules:
        description: 'python packages for pip'
        required: true 
        type: string

jobs:
  print-tag:
    runs-on: ubuntu-latest
    steps:
      - name: install a package
        run: pip install ${{ github.event.inputs.modules }}

      - name: Display the path and version
        shell: python
        run: |
          import os, platform
          print(os.environ['PATH'])
          print(platform.python_version())

      - name: display pip packages
        if:  ${{ github.event.inputs.print_modules == 'true' }} 
        run: pip list



